import = [
    "/home/falconcodes/.config/alacritty/themes/rose-pine.toml",
    "/home/falconcodes/.config/alacritty/fonts.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "none"
opacity = 0.75
blur = true

[window.padding]
x = 10
y = 10
