import = [
    "~/.config/alacritty/themes/rose-pine-moon.toml",
    "~/.config/alacritty/fonts.toml"
]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.70
blur = true

[window.padding]
x = 10
y = 10
