
[env]
TERM = "xterm-256color"

[window]
opacity = 0.85
blur = true

[window.padding]
x = 10
y = 10

[keyboard]
bindings = [
{ key = "K", mods = "Command", chars = "t"},
]

[cursor]
[cursor.style]
shape = "Block"

[general]
import = [
    "~/.config/alacritty/themes/rose-pine.toml",
    "~/.config/alacritty/fonts.toml"
]

