import = [
    "/home/falconcodes/.config/alacritty/themes/zombie-night.toml",
    "/home/falconcodes/.config/alacritty/themes/dracula.toml",
    "/home/falconcodes/.config/alacritty/themes/catppuccin.toml",
    "/home/falconcodes/.config/alacritty/fonts.toml"
]

[window]
decorations = "none"

[window.dimensions]
columns = 110
lines = 28

[window.padding]
x = 12
y = 12
