[font]
size = 20

[font.normal]
family = "GohuFont uni14 Nerd Font Mono"
style = "Regular"

[font.bold]
family = "GohuFont uni14 Nerd Font Mono"
style = "Bold"

[font.italic]
family = "GohuFont uni14 Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "GohuFont uni14 Nerd Font Mono"
style = "Bold Italic"

