import = [
    "/home/falconcodes/.config/alacritty/themes/dracula.toml",
    "/home/falconcodes/.config/alacritty/fonts.toml"
]

[window]
# decorations = "none"
opacity = 0.95

[window.dimensions]
columns = 110
lines = 28

[window.padding]
x = 12
y = 12
