# Terminal Colors
[colors]
# Default colors
[colors.primary]
background = "0x1E1D2F"
foreground = "0xD9E0EE"

[colors.cursor]
text = "0x1E1D2F"
cursor = "0xF5E0DC"

# Normal colors
[colors.normal]
black = "0x6E6C7E"
red = "0xF28FAD"
green = "0xABE9B3"
yellow = "0xFAE3B0"
blue = "0x96CDFB"
magenta = "0xF5C2E7"
cyan = "0x89DCEB"
white = "0xD9E0EE"

# Bright colors
[colors.bright]
black = "0x988BA2"
red = "0xF28FAD"
green = "0xABE9B3"
yellow = "0xFAE3B0"
blue = "0x96CDFB"
magenta = "0xF5C2E7"
cyan = "0x89DCEB"
white = "0xD9E0EE"

[colors.indexed_colors]
"0" = { index = 16, color = "0xF8BD96" }
"1" = { index = 17, color = "0xF5E0DC" }

theme = "Catppuccin"
